export type SubStep = {
  n: number;
  name: string;
  agent: string;
  gate?: string;
};

export type WorkflowStep = {
  path: string;
  label: string;
  pod: 0 | 1 | 2 | 3 | 4;
  phase: string;
  agent: string;
  /** Maturity stage this phase operates at (Crawl → Walk → Run → Autonomous). */
  maturity?: string;
  /** Primary artifact produced by the phase. */
  artifact?: string;
  /** Companion line shown in the bubble. */
  note?: string;
  /** Wireframe annotation shown at the bottom. */
  annotation?: string;
  steps?: SubStep[];
  triggers?: { to: string; label: string }[];
};

export const POD_NAMES: Record<number, string> = {
  0: "Platform",
  1: "Pod 1 · Proposal Factory",
  2: "Pod 2 · Events & Experiential",
  3: "Pod 3 · Back Office Governance",
  4: "Platform · Reference & Roadmap",
};

export const COMPANIONS: Record<1 | 2 | 3, { name: string; initial: string }> = {
  1: { name: "Sylvia", initial: "S" },
  2: { name: "Eve", initial: "E" },
  3: { name: "Oscar", initial: "O" },
};

export const WORKFLOW_STEPS: WorkflowStep[] = [
  { path: "/", label: "Login", pod: 0, phase: "Access", agent: "Platform" },
  {
    path: "/dashboard",
    label: "Dashboard",
    pod: 0,
    phase: "System at a glance",
    agent: "All companions",
  },

  // ── Pod 1 · Proposal Factory — 12 phases, 70 steps ──────────────────────
  {
    path: "/pipeline",
    label: "Pipeline / Discovery",
    pod: 1,
    phase: "Find opportunities",
    agent: "Research Analyst → Pipeline Sorter → Capability Matcher",
    maturity: "Crawl",
    artifact: "Scored opportunity funnel",
    note: "“I scan SAM and agency forecasts nightly, normalize and dedupe the feed, then score each opportunity against active sub-client capability profiles. You only see what fits.”",
    annotation:
      "Steps 1–5 are deterministic first (parse, dedupe, score) with light LLM summaries. Step 6 is the first human gate: triage what enters the active pipeline.",
    steps: [
      { n: 1, name: "Scan federal and SLED forecasts", agent: "Research Analyst" },
      { n: 2, name: "Import and normalize opportunities", agent: "Pipeline Sorter" },
      { n: 3, name: "Deduplicate opportunities", agent: "Pipeline Sorter" },
      { n: 4, name: "Match sub-client capabilities", agent: "Capability Matcher", gate: "Admin pin if needed" },
      { n: 5, name: "Create opportunity summary", agent: "Research Analyst" },
      { n: 6, name: "Opportunity triage gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/shaping",
    label: "Pre-Solicitation Shaping",
    pod: 1,
    phase: "Capture research",
    agent: "Research Analyst → Capture Support → Teaming Advisor",
    maturity: "Walk",
    artifact: "Capture brief + teaming gaps",
    note: "“Before the RFP drops I build the agency profile, incumbent and competitor intel, and the gap analysis — partner outreach is drafted, but nothing external leaves without your approval.”",
    annotation:
      "Partner outreach (steps 13–14) is gated: external communication always routes through Oscar's approval queue before it is sent.",
    steps: [
      { n: 7, name: "Agency/customer profile", agent: "Research Analyst" },
      { n: 8, name: "Incumbent lookup", agent: "Research Analyst" },
      { n: 9, name: "Competitor intelligence", agent: "Research Analyst" },
      { n: 10, name: "Agency priorities map", agent: "Research Analyst" },
      { n: 11, name: "Capture notes and assumptions", agent: "Capture Support" },
      { n: 12, name: "Capability gap analysis", agent: "Teaming Advisor" },
      { n: 13, name: "Partner outreach draft", agent: "Teaming Advisor", gate: "If external" },
      { n: 14, name: "Partner/outreach approval", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/bid-decision",
    label: "Bid Decision",
    pod: 1,
    phase: "Go/No-Go",
    agent: "Go/No-Go Analyst → Budget Tracker → Capacity Check",
    maturity: "Crawl",
    artifact: "Pwin score + pursuit recommendation",
    note: "“The scorecard blends fit, past performance, price-to-win and capacity. Oscar checks budget and delivery capacity before this lands on leadership's desk.”",
    annotation:
      "Step 18 is a hard leadership gate. Oscar logs the decision trail and flags the pursuit investment the moment a bid is approved.",
    steps: [
      { n: 15, name: "Pre-solicitation Go/No-Go draft", agent: "Go/No-Go Analyst" },
      { n: 16, name: "Commercial readiness check", agent: "Budget Tracker" },
      { n: 17, name: "Delivery capacity check", agent: "Resource/Capacity Check" },
      { n: 18, name: "Leadership Go/No-Go gate", agent: "HITL", gate: "Human gate" },
    ],
    triggers: [{ to: "/rfp-intake", label: "Bid approved → RFP Intake" }],
  },
  {
    path: "/rfp-intake",
    label: "RFP Intake",
    pod: 1,
    phase: "Parse the solicitation",
    agent: "User Action → RFP Parser → Document Controller",
    maturity: "Crawl",
    artifact: "Parsed solicitation + controlled source package",
    note: "“Upload the package and I extract sections, key dates, and submission instructions. You validate my extraction at the intake review before we build on it.”",
    annotation:
      "Oscar versions and logs the source package the moment it lands (step 23) — an immutable upload record anchors the whole pursuit.",
    steps: [
      { n: 19, name: "Upload RFP / solicitation package", agent: "User Action" },
      { n: 20, name: "Parse solicitation", agent: "RFP Parser" },
      { n: 21, name: "Extract key data points", agent: "RFP Parser", gate: "Human validates later" },
      { n: 22, name: "Submission instructions extraction", agent: "RFP Parser", gate: "Human validates later" },
      { n: 23, name: "Source package control", agent: "Document Controller" },
      { n: 24, name: "Intake review gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/compliance",
    label: "Compliance / Strategy",
    pod: 1,
    phase: "Matrix + win themes",
    agent: "Compliance Checker → Meeting Scheduler → Win Theme Generator",
    maturity: "Walk",
    artifact: "Compliance matrix + win theme set",
    note: "“Every requirement gets a matrix row with evidence. Material gaps are flagged to Oscar immediately — nothing hides in a spreadsheet.”",
    annotation:
      "The strategy review gate (step 31) locks the compliance matrix, win themes, and review cadence before drafting begins.",
    steps: [
      { n: 25, name: "Build compliance matrix", agent: "Compliance Checker" },
      { n: 26, name: "Evaluation criteria map", agent: "Compliance Checker" },
      { n: 27, name: "Risk and gap log", agent: "Compliance Checker", gate: "Material gaps only" },
      { n: 28, name: "Proposal schedule and review cadence", agent: "Meeting Scheduler" },
      { n: 29, name: "Win themes", agent: "Win Theme Generator" },
      { n: 30, name: "Differentiators and ghost themes", agent: "Win Theme Generator" },
      { n: 31, name: "Strategy review gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/qa-amendments",
    label: "Q&A / Amendments",
    pod: 1,
    phase: "Clarifications & change control",
    agent: "Q&A Analyst → RFP Parser Phase 2 → Audit + Budget Impact",
    maturity: "Walk",
    artifact: "Approved Q&A package + amendment impact reports",
    note: "“I collect clarification questions and prepare the package — Oscar routes it for approval before anything goes to the customer. Amendments get a diff and an impact assessment.”",
    annotation:
      "A material amendment (step 37) can retrigger the Go/No-Go — scope, cost, or compliance changes never slip through silently.",
    steps: [
      { n: 32, name: "Collect clarification questions", agent: "Q&A Analyst" },
      { n: 33, name: "Prepare Q&A package", agent: "Q&A Analyst", gate: "Before customer-facing" },
      { n: 34, name: "Q&A approval gate", agent: "HITL", gate: "Human gate" },
      { n: 35, name: "Customer response intake", agent: "Q&A Analyst" },
      { n: 36, name: "Amendment diff", agent: "RFP Parser Phase 2" },
      { n: 37, name: "Amendment impact assessment", agent: "Audit + Budget Impact", gate: "Material impact only" },
      { n: 38, name: "Revised Go/No-Go if material", agent: "HITL", gate: "If material" },
    ],
  },
  {
    path: "/tech-cost",
    label: "Technical / Cost Build",
    pod: 1,
    phase: "First full draft",
    agent: "Outline Agent → Technical Drafter → Cost Drafter → Layout Designer",
    maturity: "Walk",
    artifact: "First technical + cost draft",
    note: "“Outline first — you approve the skeleton before I draft a word of prose. The cost draft runs in parallel and Oscar baselines it for margin checks.”",
    annotation:
      "Step 45 is the cross-pod seam: if the RFP contains event scope, Eve's intake opens here and the event budget must reconcile to this proposal's BOE.",
    steps: [
      { n: 39, name: "Create technical outline", agent: "Technical Outline Agent" },
      { n: 40, name: "Outline approval gate", agent: "HITL", gate: "Human gate" },
      { n: 41, name: "Generate supporting docs", agent: "Supporting Docs Generator", gate: "Human validates accuracy" },
      { n: 42, name: "Partner data calls", agent: "Teaming Advisor", gate: "External release approval" },
      { n: 43, name: "First technical draft", agent: "Technical Drafter" },
      { n: 44, name: "Initial cost draft", agent: "Cost Drafter", gate: "Pricing baseline follows" },
      { n: 45, name: "Event scope handoff if needed", agent: "Cross-Pod Trigger", gate: "If budget impact" },
      { n: 46, name: "Layout draft", agent: "Layout Designer" },
      { n: 47, name: "First draft review gate", agent: "HITL", gate: "Human gate" },
    ],
    triggers: [{ to: "/event-intake", label: "Event scope → Eve's intake" }],
  },
  {
    path: "/revision",
    label: "Revision Cycle",
    pod: 1,
    phase: "Color-team reviews",
    agent: "Review Coordinator → Technical Drafter P2 → Cost Drafter P2 → QA / 508",
    maturity: "Walk",
    artifact: "Consolidated review actions + revised volumes",
    note: "“Pink, Red, Gold — I consolidate every review into deduped actions and rerun only the affected sections, so tokens stay lean and versions stay clean.”",
    annotation:
      "Reviewer feedback can be exported to Word and re-imported — the next agent run reads the human's edits. Compliance and QA re-check only material changes.",
    steps: [
      { n: 48, name: "Consolidate reviewer comments", agent: "Review Coordinator" },
      { n: 49, name: "Revised technical draft", agent: "Technical Drafter Phase 2", gate: "Material changes only" },
      { n: 50, name: "Revised cost draft", agent: "Cost Drafter Phase 2", gate: "If margin/price threshold" },
      { n: 51, name: "Revised layout", agent: "Layout Designer Phase 2" },
      { n: 52, name: "Compliance recheck", agent: "Compliance Checker", gate: "Material gaps only" },
      { n: 53, name: "QA and accessibility review", agent: "QA / 508 Agent", gate: "Unresolved issues only" },
      { n: 54, name: "Compliance / QA gate", agent: "HITL", gate: "If issues remain" },
    ],
  },
  {
    path: "/finalization",
    label: "Finalization",
    pod: 1,
    phase: "Lock the volumes",
    agent: "Final Technical → Final Cost → Final Layout → Final Review",
    maturity: "Crawl",
    artifact: "Final volumes + executive review package",
    note: "“Final volumes are assembled and the commercial readiness summary goes to Oscar — final cost is always a human lock, never an agent decision.”",
    annotation:
      "Step 56 (final cost) and step 60 (final approval) are mandatory gates. Oscar validates margin, locks the cost version, and routes the executive package.",
    steps: [
      { n: 55, name: "Final technical volume", agent: "Final Technical Agent", gate: "Unless material" },
      { n: 56, name: "Final cost volume", agent: "Final Cost Agent", gate: "Human gate" },
      { n: 57, name: "Final proposal package", agent: "Final Layout Agent" },
      { n: 58, name: "Commercial readiness summary", agent: "Budget Tracker", gate: "If pricing final" },
      { n: 59, name: "Executive review package", agent: "Final Review Agent", gate: "Human gate" },
      { n: 60, name: "Final approval gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/submission",
    label: "Submission",
    pod: 1,
    phase: "Deliver officially",
    agent: "Proposal Submission Agent → User Action → Document Controller",
    maturity: "Crawl",
    artifact: "Submitted package + archived receipt",
    note: "“I assemble the package and verify the portal checklist — but the official submit button is yours. The receipt is archived the moment it comes back.”",
    annotation:
      "Step 63 is always a human action. Oscar locks the final document versions at submission so the audit trail matches exactly what was sent.",
    steps: [
      { n: 61, name: "Submission package assembly", agent: "Proposal Submission Agent" },
      { n: 62, name: "Portal / delivery checklist", agent: "Proposal Submission Agent" },
      { n: 63, name: "Official submission", agent: "User Action", gate: "Human action" },
      { n: 64, name: "Receipt and archive", agent: "Document Controller" },
    ],
  },
  {
    path: "/post-submit",
    label: "Post-Submit",
    pod: 1,
    phase: "Track, orals, negotiate",
    agent: "Post-Submit Tracker → Orals Coach → Negotiation Prep",
    maturity: "Walk",
    artifact: "Status log + orals / negotiation packages",
    note: "“I monitor status and prep the debrief. If orals are triggered, the deck and rehearsal package are drafted — you approve anything client-facing.”",
    annotation:
      "Buyer communications and the orals package are gated before going external; negotiation positions are always human-decided.",
    steps: [
      { n: 65, name: "Status monitoring", agent: "Post-Submit Tracker" },
      { n: 66, name: "Buyer communications and debrief prep", agent: "Communications / Debrief Support", gate: "If external" },
      { n: 67, name: "Orals trigger assessment", agent: "Orals Coach" },
      { n: 68, name: "Orals deck and rehearsal package", agent: "Orals Coach + Presentation Builder", gate: "Before client-facing" },
      { n: 69, name: "Negotiation package", agent: "Negotiation Prep", gate: "Human decides positions" },
    ],
  },
  {
    path: "/award",
    label: "Award / Handoff",
    pod: 1,
    phase: "Win → delivery",
    agent: "Kickoff Planner → Cross-Pod Trigger",
    maturity: "Crawl",
    artifact: "Kickoff plan + delivery baseline",
    note: "“Award received — I draft the kickoff plan and transition baseline. Event scope goes to Eve, budgets convert at Oscar, and delivery begins on your readiness gate.”",
    annotation:
      "Step 70 is the operational readiness gate. This is the main cross-pod seam: Pod 1 closes, Pod 2 opens delivery, Pod 3 converts budgets and locks the audit trail.",
    steps: [
      { n: 70, name: "Award and kickoff handoff", agent: "Kickoff Planner", gate: "Human readiness gate" },
    ],
    triggers: [
      { to: "/event-intake", label: "Event scope → spin up Eve" },
      { to: "/budget", label: "Convert to delivery baseline" },
    ],
  },

  // ── Pod 2 · Events & Experiential — 8 phases, 48 steps ──────────────────
  {
    path: "/event-intake",
    label: "Intake & Concept",
    pod: 2,
    phase: "Brief to concept",
    agent: "Event Intake Parser → Strategy Support → Concept Developer",
    maturity: "Walk",
    artifact: "Event brief + approved concept",
    note: "“Send me a scope from a won proposal or a standalone brief. I extract requirements, classify audience and format, and generate concepts — creative direction is always your call.”",
    annotation:
      "Concept approval (step 10) is the first Pod 2 gate. Strategy and KPIs are gated whenever the work is client-facing.",
    steps: [
      { n: 1, name: "Event scope received", agent: "Cross-Pod Trigger" },
      { n: 2, name: "Upload event brief / scope", agent: "Event Intake Parser" },
      { n: 3, name: "Extract event requirements", agent: "Event Intake Parser" },
      { n: 4, name: "Define event objectives", agent: "Strategy Support", gate: "If client-facing" },
      { n: 5, name: "Audience and format classification", agent: "Event Intake Parser" },
      { n: 6, name: "Route event workflow", agent: "Eve" },
      { n: 7, name: "Generate concepts", agent: "Concept Developer" },
      { n: 8, name: "Mood board / visual direction", agent: "Concept Developer", gate: "Human reviews creative" },
      { n: 9, name: "Event strategy / CSFs / KPIs", agent: "Strategy Support", gate: "If client-facing" },
      { n: 10, name: "Concept approval gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/venue-pitch",
    label: "Venue & Pitch",
    pod: 2,
    phase: "Where + the pitch",
    agent: "Venue Scout → Logistics → Catering / Travel → Presentation Builder",
    maturity: "Walk",
    artifact: "Venue shortlist + client pitch deck",
    note: "“I scout venues, check logistics feasibility, and build the pitch deck. The client-facing deck ships only after your approval.”",
    annotation:
      "Catering and travel plans are drafted here but spend approval happens later, at Oscar's budget gates.",
    steps: [
      { n: 11, name: "Venue / location research", agent: "Venue Scout" },
      { n: 12, name: "Site logistics feasibility", agent: "Logistics Coordinator", gate: "Material concerns only" },
      { n: 13, name: "Catering and hospitality plan", agent: "Catering/Hospitality Support", gate: "Spend approval later" },
      { n: 14, name: "Travel / lodging plan", agent: "Travel Coordinator", gate: "Spend approval later" },
      { n: 15, name: "Client/event pitch deck", agent: "Presentation Builder", gate: "Human approves deck" },
      { n: 16, name: "Venue / pitch approval gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/production",
    label: "Production Planning",
    pod: 2,
    phase: "Budget, timeline, vendors",
    agent: "Budget Analyst → Timeline Manager → Vendor / Talent Coordinators",
    maturity: "Walk",
    artifact: "Baseline budget + run-of-show + vendor RFQs",
    note: "“The draft budget aligns to the proposal BOE — Oscar flags any margin variance. Run-of-show, stage plans, and vendor RFQs all route through human review before execution.”",
    annotation:
      "Step 18 is the cross-pod cost check: the event budget must reconcile to the proposal's basis of estimate. Step 26 gates the whole plan.",
    steps: [
      { n: 17, name: "Draft event budget", agent: "Budget Analyst", gate: "Baseline approval follows" },
      { n: 18, name: "Align event cost to proposal BOE", agent: "Budget Analyst + Cost Drafter", gate: "If proposal pricing affected" },
      { n: 19, name: "Sponsor revenue model", agent: "Sponsor Sales", gate: "Before outreach" },
      { n: 20, name: "Production timeline", agent: "Timeline Manager" },
      { n: 21, name: "Run-of-show", agent: "Timeline Manager", gate: "Human review" },
      { n: 22, name: "Logistics plan", agent: "Logistics Coordinator", gate: "Spend/vendor gates later" },
      { n: 23, name: "Stage / AV / technical plan", agent: "Stage Manager", gate: "Safety/quality review" },
      { n: 24, name: "Vendor RFQ package", agent: "Vendor Coordinator", gate: "External outreach approval" },
      { n: 25, name: "Speakers / talent sourcing", agent: "Talent Scout", gate: "Human approves selections" },
      { n: 26, name: "Production budget / timeline gate", agent: "HITL", gate: "Human gate" },
    ],
    triggers: [{ to: "/budget", label: "BOE variance → Oscar" }],
  },
  {
    path: "/comms-registration",
    label: "Comms & Registration",
    pod: 2,
    phase: "Audience launch",
    agent: "Registration Manager → Communications Drafter → Social Media Manager",
    maturity: "Run",
    artifact: "Registration site + comms calendar",
    note: "“Registration, attendee comms, and the social calendar are drafted and staged — the public launch gate is the point of no return, and it's yours.”",
    annotation:
      "Every public-facing asset (registration launch, attendee copy, social content) carries its own human approval before step 31 opens the doors.",
    steps: [
      { n: 27, name: "Registration setup", agent: "Registration Manager", gate: "Human approves launch" },
      { n: 28, name: "Attendee communications", agent: "Communications Drafter", gate: "Approves public copy" },
      { n: 29, name: "Social content calendar", agent: "Social Media Manager", gate: "Approves content" },
      { n: 30, name: "Crew call sheets and internal briefs", agent: "Internal Comms", gate: "Unless sensitive" },
      { n: 31, name: "Public launch approval gate", agent: "HITL", gate: "Human gate" },
    ],
  },
  {
    path: "/talent-sponsors",
    label: "Talent / Sponsors / Activation",
    pod: 2,
    phase: "Commercial layer",
    agent: "Sponsor Sales → Activation Planner → Promo/Fulfillment",
    maturity: "Walk",
    artifact: "Signed sponsors + activation plan",
    note: "“Sponsor outreach packages, booth and floorplan concepts, promo fulfillment — all drafted. Contracts and spend converge on one Oscar-routed gate.”",
    annotation:
      "Step 35 is a compound gate: vendor, talent, and sponsor contracts are approved together so budget exposure is visible in one place.",
    steps: [
      { n: 32, name: "Promo items and fulfillment plan", agent: "Promo/Fulfillment Support", gate: "Spend approval" },
      { n: 33, name: "Activation / booth / floorplan", agent: "Activation Planner", gate: "Creative/spend gate" },
      { n: 34, name: "Sponsor outreach package", agent: "Sponsor Sales", gate: "Approves outreach" },
      { n: 35, name: "Vendor / talent / sponsor contract gate", agent: "HITL", gate: "Human gate" },
    ],
    triggers: [{ to: "/approvals", label: "Contracts → approval queue" }],
  },
  {
    path: "/execution-prep",
    label: "Execution Prep",
    pod: 2,
    phase: "Final readiness",
    agent: "Stage Manager → Registration Manager → Internal Comms",
    maturity: "Run",
    artifact: "Rehearsal plan + live-readiness checklist",
    note: "“Rehearsal scheduled, badging tested, live comms stood up. Check-in readiness is validated by a human before we go live.”",
    annotation:
      "A short phase by design: three steps that convert the approved plan into a verified, ready-to-run operation.",
    steps: [
      { n: 36, name: "Rehearsal plan", agent: "Stage Manager" },
      { n: 37, name: "Check-in and badging readiness", agent: "Registration Manager", gate: "Human validates" },
      { n: 38, name: "Live comms setup", agent: "Internal Comms" },
    ],
  },
  {
    path: "/execution",
    label: "Execution",
    pod: 2,
    phase: "Live event",
    agent: "Status Reporter → Budget Analyst → Eve / Event Team",
    maturity: "Run",
    artifact: "Live status log + budget actuals",
    note: "“Live: I stream status, log issues, and track budget actuals against the baseline. Threshold breaches escalate — but live decisions stay with the humans on the floor.”",
    annotation:
      "Agents report and coordinate during execution; the event team runs the show. Oscar watches budget actuals for threshold breaches only.",
    steps: [
      { n: 39, name: "Live status and issue log", agent: "Status Reporter", gate: "Human live decisions" },
      { n: 40, name: "Live budget actuals", agent: "Budget Analyst", gate: "Threshold only" },
      { n: 41, name: "Executive check-in report", agent: "Status Reporter", gate: "Unless client-facing" },
      { n: 42, name: "Event execution coordination", agent: "Eve / Event Team", gate: "Human runs event" },
    ],
  },
  {
    path: "/closeout",
    label: "Closeout",
    pod: 2,
    phase: "Impact & feedback loop",
    agent: "Data Analyst → Impact Analyst → Post-Event Reporter",
    maturity: "Walk",
    artifact: "ROI / impact report + proof points",
    note: "“Surveys, media monitoring, budget reconciliation, and the impact report — then the best part: validated proof points flow back to Sylvia's past-performance library for the next proposal.”",
    annotation:
      "Step 48 closes the loop across pods: lessons and proof points return to Pod 1 as reusable past-performance evidence, validated by a human.",
    steps: [
      { n: 43, name: "Survey and attendee data collection", agent: "Data Analyst" },
      { n: 44, name: "Media and social monitoring", agent: "Social Media Manager" },
      { n: 45, name: "Budget reconciliation", agent: "Budget Analyst", gate: "If variance" },
      { n: 46, name: "ROI / impact report", agent: "Impact Analyst", gate: "Human validates insights" },
      { n: 47, name: "Closeout report and recommendations", agent: "Post-Event Reporter", gate: "Approves final report" },
      { n: 48, name: "Lessons and proof points to Pod 1", agent: "Cross-Pod Feedback", gate: "Human validates" },
    ],
    triggers: [{ to: "/pipeline", label: "Proof points → Pod 1 library" }],
  },

  // ── Pod 3 · Back Office Governance — 6 areas ─────────────────────────────
  {
    path: "/approvals",
    label: "Approval Queue",
    pod: 3,
    phase: "Every gate, one queue",
    agent: "Approval Router",
    maturity: "Crawl",
    artifact: "Routed decisions with full context",
    note: "“Every human gate across both pods lands here with its context attached — decision, budget exposure, and the evidence trail. Nothing is approved in a vacuum.”",
    annotation:
      "The Approval Router is trigger-driven: gates arrive from Pod 1 and Pod 2 automatically, each carrying its audit requirement and budget impact.",
    steps: [
      { n: 1, name: "Pursuit / Go-No-Go decisions", agent: "From Pod 1 · Bid Decision", gate: "Always" },
      { n: 2, name: "External comms (Q&A, outreach, decks)", agent: "From Pods 1 & 2", gate: "Always before send" },
      { n: 3, name: "Cost baselines and final pricing", agent: "From Pod 1 · Cost", gate: "Always" },
      { n: 4, name: "Event concept / budget / launch", agent: "From Pod 2", gate: "Always" },
      { n: 5, name: "Vendor / talent / sponsor contracts", agent: "From Pod 2", gate: "Always" },
    ],
  },
  {
    path: "/audit",
    label: "Audit Trail",
    pod: 3,
    phase: "Immutable record",
    agent: "Audit Analyst + Document Controller",
    maturity: "Walk",
    artifact: "Decision trail + before/after snapshots",
    note: "“Every upload, amendment, decision, and handoff is logged immutably. Ask me any 'why' about a pursuit and I can replay the evidence.”",
    annotation:
      "Amendments trigger before/after snapshots; compliance gaps carry evidence logs; external communications carry approval records.",
    steps: [
      { n: 1, name: "Immutable upload log", agent: "On RFP intake" },
      { n: 2, name: "Decision trail (Go/Hold/No-Go)", agent: "On every gate" },
      { n: 3, name: "Amendment before/after snapshots", agent: "On amendment" },
      { n: 4, name: "Compliance requirement evidence", agent: "On gap flagged" },
      { n: 5, name: "External comms approval log", agent: "On external send" },
      { n: 6, name: "Cross-pod handoff log", agent: "On pod trigger" },
    ],
  },
  {
    path: "/budget",
    label: "Budget Guardrails",
    pod: 3,
    phase: "Margin protection",
    agent: "Budget Tracker",
    maturity: "Walk",
    artifact: "Baselines, variance flags, locked pricing",
    note: "“I baseline every cost draft, validate margin before any lock, and flag variance between event budgets and proposal BOEs. Final pricing is always human-locked.”",
    annotation:
      "Thresholds are configurable per maturity stage: Crawl requires approval often, Run only escalates threshold breaches.",
    steps: [
      { n: 1, name: "Cost baseline creation", agent: "On first cost draft" },
      { n: 2, name: "Pursuit investment flags", agent: "On Go decision" },
      { n: 3, name: "Event ↔ proposal BOE variance", agent: "On cross-pod cost" },
      { n: 4, name: "Margin / price threshold checks", agent: "On revision" },
      { n: 5, name: "Final baseline lock", agent: "On final cost", gate: "Always" },
      { n: 6, name: "Live actuals vs baseline", agent: "During events", gate: "Threshold only" },
    ],
  },
  {
    path: "/documents",
    label: "Document Control",
    pod: 3,
    phase: "Versions & locks",
    agent: "Document Controller",
    maturity: "Crawl",
    artifact: "Controlled, versioned document set",
    note: "“Source packages are versioned on arrival, working drafts stay editable, and final volumes lock at submission — what was sent is exactly what the archive shows.”",
    annotation:
      "Document locks follow the workflow: source control at intake, Q&A lock at approval, final lock at submission, receipt archive after.",
    steps: [
      { n: 1, name: "Source package versioning", agent: "On upload" },
      { n: 2, name: "Amendment diff storage", agent: "On amendment" },
      { n: 3, name: "Q&A package lock", agent: "On approval", gate: "Before send" },
      { n: 4, name: "Cost version log", agent: "On each cost draft" },
      { n: 5, name: "Final volume lock", agent: "On submission", gate: "Always" },
      { n: 6, name: "Receipt and record archive", agent: "Post-submit" },
    ],
  },
  {
    path: "/access",
    label: "Access & RBAC",
    pod: 3,
    phase: "Tenant isolation",
    agent: "RBAC Manager",
    maturity: "Crawl",
    artifact: "Scoped visibility per sub-client",
    note: "“Sub-clients only ever see their own pursuits. Capability matches, pipeline visibility, and dashboards are scoped — admin pins are logged and auditable.”",
    annotation:
      "RBAC is enforced at the data layer, not the UI: every trigger that touches visibility runs through the RBAC Manager first.",
    steps: [
      { n: 1, name: "Tenant-scoped pipeline visibility", agent: "On pipeline change" },
      { n: 2, name: "Sub-client match / pin rules", agent: "On capability match", gate: "Admin pin if needed" },
      { n: 3, name: "Role-based dashboard scoping", agent: "Continuous" },
      { n: 4, name: "Cross-client concern escalation", agent: "On conflict", gate: "Human gate" },
    ],
  },
  {
    path: "/maturity",
    label: "Maturity Model",
    pod: 3,
    phase: "Crawl → Walk → Run → Autonomous",
    agent: "Dashboard Aggregator",
    maturity: "All stages",
    artifact: "Per-area autonomy dial",
    note: "“Autonomy is earned per workflow area, not granted globally. The dial only moves up when the audit trail proves an area is reliable — and it can move back down.”",
    annotation:
      "Crawl: approve everything. Walk: approve material items. Run: threshold-only escalation. Autonomous: agents act, humans audit. Each phase screen shows its current stage.",
    steps: [
      { n: 1, name: "Crawl — human approves every gate", agent: "Default for new areas" },
      { n: 2, name: "Walk — material-only gates", agent: "Earned with evidence" },
      { n: 3, name: "Run — threshold escalation only", agent: "Earned with evidence" },
      { n: 4, name: "Autonomous — agents act, humans audit", agent: "Rare, revocable", gate: "Periodic human audit" },
    ],
  },

  // ── Reference & Roadmap — Executive Overview, master map, connectors, future pods ──
  {
    path: "/overview",
    label: "Executive Overview",
    pod: 4,
    phase: "Two layers, one philosophy",
    agent: "Platform architecture",
    artifact: "Architecture + build execution model",
    annotation:
      "The workbook separates the executive architecture map (this layer) from the detailed pod build instructions — linked, but never mixed.",
    steps: [
      { n: 1, name: "Layer 1 · Platform Architecture", agent: "Pods, companions, Pod 3 governance, MCP strategy" },
      { n: 2, name: "Layer 2 · Build Execution", agent: "Pod 1 70-step · Pod 2 detailed · Pod 3 triggers" },
      { n: 3, name: "Build philosophy", agent: "Crawl → Walk → Run → Autonomous · autonomy is earned", gate: "Maturity metrics" },
      { n: 4, name: "Integration philosophy", agent: "Governed MCP connector families, no brittle one-offs" },
      { n: 5, name: "Cost philosophy", agent: "Deterministic logic before LLM calls", gate: "Token budget" },
      { n: 6, name: "Brand", agent: "The Proposal Factory™ mark on all future docs and decks" },
      { n: 7, name: "Sylvia · Pod 1 companion", agent: "Pursuit orchestrator — never runs finance or events", gate: "Routes to Oscar/Eve" },
      { n: 8, name: "Eve · Pod 2 companion", agent: "Event orchestrator — never signs contracts or spend", gate: "Routes to Oscar" },
      { n: 9, name: "Oscar · Pod 3 companion", agent: "Governance layer — wraps pods, never writes proposals" },
      { n: 10, name: "Future companions", agent: "Created from pod template, inherit all governance rails" },
    ],
    triggers: [{ to: "/master-map", label: "Cross-pod master map" }],
  },
  {
    path: "/master-map",
    label: "Cross-Pod Master Map",
    pod: 4,
    phase: "17 orchestration moments",
    agent: "Lead agent per moment · collaborating pods",
    artifact: "Executive orchestration map",
    annotation:
      "The executive view of the same work: each moment names its lead agent, collaborating agents, MCP layer, and human gate. Detail lives on the pod screens.",
    steps: [
      { n: 1, name: "Opportunity Discovery", agent: "Research Analyst", gate: "Human validates pipeline" },
      { n: 2, name: "Pipeline Classification", agent: "Pipeline Sorter", gate: "Human validates priority" },
      { n: 3, name: "Pre-Solicitation Go/No-Go", agent: "Go/No-Go Analyst", gate: "Human pursuit decision" },
      { n: 4, name: "Event Scope Detected in RFP", agent: "RFP Parser → Eve", gate: "Advisory unless price impact" },
      { n: 5, name: "RFP Intake", agent: "RFP Parser / Intake Agent", gate: "Human validates completeness" },
      { n: 6, name: "Compliance Setup", agent: "Compliance Checker", gate: "Material gaps only" },
      { n: 7, name: "Strategy / Win Themes", agent: "Win Theme Generator", gate: "Human approves messaging" },
      { n: 8, name: "Q&A / Amendment Impact", agent: "Q&A Analyst / Parser Phase 2", gate: "Human approves interpretation" },
      { n: 9, name: "Event Budget for Proposal", agent: "Cost Drafter + Budget Analyst", gate: "Required if threshold hit" },
      { n: 10, name: "Orals / Interview Presentation", agent: "Orals Coach + Presentation Builder", gate: "Human approves deck" },
      { n: 11, name: "Final Cost", agent: "Final Cost", gate: "Required human gate" },
      { n: 12, name: "Submission", agent: "Proposal Submission", gate: "Human submits officially" },
      { n: 13, name: "Award / Kickoff", agent: "Kickoff Planner", gate: "Human readiness gate" },
      { n: 14, name: "Event Intake", agent: "Event Intake Parser", gate: "If client-facing" },
      { n: 15, name: "Event Budget", agent: "Budget Analyst", gate: "Human approves budget" },
      { n: 16, name: "Registration / Attendee Mgmt", agent: "Registration Manager", gate: "Human approves public launch" },
      { n: 17, name: "Future Pod Launch / Delivery", agent: "Future pod agents", gate: "Human gates by risk" },
    ],
  },
  {
    path: "/connectors",
    label: "MCP / Integration Gateway",
    pod: 4,
    phase: "16 connector families",
    agent: "Governed connectors, not one-off APIs",
    artifact: "Shared integration layer",
    annotation:
      "Agents call governed connector families instead of brittle one-off tool integrations. Every family carries tenant scope, audit, and release governance.",
    steps: [
      { n: 1, name: "Document MCP", agent: "Drive, SharePoint, OneDrive, Box, Dropbox · Document Controller", gate: "Phase 1" },
      { n: 2, name: "Work Management MCP", agent: "Asana, Monday, ClickUp, Jira · Approval Router", gate: "Phase 1" },
      { n: 3, name: "Finance MCP", agent: "QuickBooks, Xero, Bill.com, Stripe, Square · Budget Tracker", gate: "Phase 1" },
      { n: 4, name: "Communications MCP", agent: "Gmail, Outlook, Slack, Teams, SendGrid, Twilio", gate: "Phase 1" },
      { n: 5, name: "Calendar MCP", agent: "Google Calendar, Outlook, Calendly", gate: "Phase 1" },
      { n: 6, name: "Event Registration MCP", agent: "Eventbrite, Cvent, Bizzabo, Splash · Eve", gate: "Phase 2" },
      { n: 7, name: "Social / Listening MCP", agent: "Meta, LinkedIn, Sprout, Hootsuite, Brandwatch", gate: "Phase 2 / Future" },
      { n: 8, name: "CRM MCP", agent: "HubSpot, Salesforce, Airtable", gate: "Phase 2" },
      { n: 9, name: "Creative Asset MCP", agent: "Canva, Adobe, Cloudinary, DAM, Bynder", gate: "Phase 2" },
      { n: 10, name: "Ad Platform MCP", agent: "Google, Meta, LinkedIn, TikTok, DV360, Trade Desk", gate: "Future" },
      { n: 11, name: "Research / Survey MCP", agent: "Qualtrics, SurveyMonkey, SPSS, Tableau", gate: "Future" },
      { n: 12, name: "CMS / Web MCP", agent: "WordPress, HubSpot, Webflow, GitHub, Vercel", gate: "Future" },
      { n: 13, name: "Identity / Access MCP", agent: "Okta, Azure AD, Google Workspace · RBAC Manager", gate: "Future / Enterprise" },
      { n: 14, name: "Audit / Observability MCP", agent: "Sentry, Datadog, GCS/S3 Archive · All agents via Oscar", gate: "Phase 1/2" },
    ],
  },
  {
    path: "/future-pods",
    label: "Future Pods",
    pod: 4,
    phase: "9 marketing + 8 industry families",
    agent: "New pods inherit rails — never fork architecture",
    artifact: "Reusable pod template",
    annotation:
      "Every future pod inherits companion, agent registry, gates, Pod 3 governance, MCP map, dashboards, and token rules. Nothing forks the architecture.",
    steps: [
      { n: 1, name: "Advertising", agent: "Media Planner, Bid Manager, Ad Copy Optimizer", gate: "Marketing · spend gate" },
      { n: 2, name: "PR / Communications", agent: "Press Writer, Coverage Tracker, Crisis Monitor", gate: "Marketing · release gate" },
      { n: 3, name: "Creative / Content", agent: "Copy Amplifier, Asset Manager, QA Brand Guardian", gate: "Marketing · brand gate" },
      { n: 4, name: "Research", agent: "Survey Designer, Trend Forecaster, Data Analyst", gate: "Marketing · methodology" },
      { n: 5, name: "Brand / Campaign Strategy", agent: "Positioning Agent, Messaging Architect", gate: "Marketing · strategy gate" },
      { n: 6, name: "Direct / CRM Marketing", agent: "Personalization Engine, Journey Builder", gate: "Marketing · launch gate" },
      { n: 7, name: "Web / Digital Experience", agent: "Code Assistant, Security Scanner, Deploy Manager", gate: "Marketing · deploy gate" },
      { n: 8, name: "Video / Production", agent: "Script Developer, Edit Assistant, Review Coordinator", gate: "Marketing · final cut" },
      { n: 9, name: "Social / Influencer", agent: "Content Scheduler, Influencer Scout, Trend Spotter", gate: "Marketing · crisis gate" },
      { n: 10, name: "Construction", agent: "Estimator, Permit Tracker, Schedule Builder", gate: "Industry · estimate/safety" },
      { n: 11, name: "Janitorial / Facilities", agent: "Staffing Scheduler, Quality Inspector, Route Planner", gate: "Industry · staffing/QA" },
      { n: 12, name: "Technology / Cyber", agent: "Solution Architect, Security Reviewer, Compliance Tracker", gate: "Industry · security/deploy" },
      { n: 13, name: "Staffing", agent: "Candidate Matcher, Credential Checker, Payroll Handoff", gate: "Industry · credentialing" },
      { n: 14, name: "Financial Services", agent: "Compliance Reviewer, Risk Analyst, Audit Packager", gate: "Industry · compliance" },
      { n: 15, name: "Healthcare / Home Health", agent: "Referral Intake, Care Plan Support, Billing", gate: "Industry · care/billing" },
      { n: 16, name: "Logistics / Transportation", agent: "Route Planner, Fleet Scheduler, Dispatch Assist", gate: "Industry · safety" },
      { n: 17, name: "Training / Education", agent: "Curriculum Planner, Assessment Builder, Certificates", gate: "Industry · curriculum" },
    ],
  },
  {
    path: "/roadmap",
    label: "Implementation Roadmap",
    pod: 4,
    phase: "7 build phases",
    agent: "Daniel/JTS + Delano",
    artifact: "Phased delivery plan",
    annotation:
      "Pod 1's revenue engine ships first. Pod 3's trigger engine and the MCP gateway follow; future pods are a template exercise, not new architecture.",
    steps: [
      { n: 1, name: "Phase 1 · Protect Pod 1 revenue engine", agent: "2–4 wks · Cost Drafter → Budget Tracker, final cost, doc lock", gate: "Don't overbuild" },
      { n: 2, name: "Phase 1A · Workflow visibility", agent: "1 wk · 70-step registry, handoff map, maturity per step", gate: "Steps not always mandatory" },
      { n: 3, name: "Phase 2 · Activate Pod 2 cross-pod value", agent: "3–5 wks · Event budget to BOE, orals deck workflow", gate: "No full event ERP yet" },
      { n: 4, name: "Phase 2A · Pod 2 detailed workflow", agent: "2–3 wks · Intake through closeout with Eve", gate: "Modular by event type" },
      { n: 5, name: "Phase 3 · Pod 3 trigger engine", agent: "2–3 wks · Threshold rules, approval routing, audit events", gate: "Not a linear workflow" },
      { n: 6, name: "Phase 4 · MCP / Integration Gateway", agent: "3–6 wks · MCP-lite services, auth, audit, rate limits", gate: "Start manual/one-way" },
      { n: 7, name: "Phase 5 · Future pod template", agent: "2–3 wks · Companion, agent registry, gates, MCP map", gate: "Inherit, don't fork" },
    ],
  },
  {
    path: "/reference",
    label: "Architecture Notes",
    pod: 4,
    phase: "Guiding principles + data dictionary",
    agent: "Platform doctrine",
    artifact: "Design rules for every future build",
    annotation:
      "The data dictionary defines every column of the model: lead pod, lead agent, primary output, collaborating agents, companion role, governance, MCP connector, human gate, maturity, token rule, build priority, and future-pod reuse.",
    steps: [
      { n: 1, name: "Two-layer workbook", agent: "Master map is the map; pod tabs are build instructions" },
      { n: 2, name: "Event-triggered workflows", agent: "Rerun only affected agents — never fire everything" },
      { n: 3, name: "Pod 3 as governance", agent: "Oscar wraps pods; it is not a sequential flow" },
      { n: 4, name: "MCP preference", agent: "Shared connector families over one-off APIs" },
      { n: 5, name: "Human gates by risk", agent: "Money, compliance, access, external release, submission, delivery", gate: "Always human" },
      { n: 6, name: "Token optimization", agent: "Deterministic first; LLMs for judgment and narrative", gate: "Cost posture" },
      { n: 7, name: "Autonomy is earned", agent: "Per agent, per step, per sub-client — revocable" },
      { n: 8, name: "Future pod rails", agent: "New pods inherit everything; expansion without breakage" },
      { n: 9, name: "The Proposal Factory™ brand", agent: "Trademark mark on all docs, decks, PDFs" },
    ],
  },
];

export const stepIndex = (path: string) => WORKFLOW_STEPS.findIndex((s) => s.path === path);
