/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StartRouteImport } from './routes/start'
import { Route as AppAccessRouteImport } from './routes/_app.access'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAwardRouteImport } from './routes/_app.award'
import { Route as AppBidDecisionRouteImport } from './routes/_app.bid-decision'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as AppBulkEditRouteImport } from './routes/_app.bulk-edit'
import { Route as AppCloseoutRouteImport } from './routes/_app.closeout'
import { Route as AppCommsRegistrationRouteImport } from './routes/_app.comms-registration'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppConnectorsRouteImport } from './routes/_app.connectors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppEventIntakeRouteImport } from './routes/_app.event-intake'
import { Route as AppExecutionRouteImport } from './routes/_app.execution'
import { Route as AppExecutionPrepRouteImport } from './routes/_app.execution-prep'
import { Route as AppFinalizationRouteImport } from './routes/_app.finalization'
import { Route as AppFuturePodsRouteImport } from './routes/_app.future-pods'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppMasterMapRouteImport } from './routes/_app.master-map'
import { Route as AppMaturityRouteImport } from './routes/_app.maturity'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppPod1RouteImport } from './routes/_app.pod1'
import { Route as AppPod2RouteImport } from './routes/_app.pod2'
import { Route as AppPod3RouteImport } from './routes/_app.pod3'
import { Route as AppPostSubmitRouteImport } from './routes/_app.post-submit'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppQaAmendmentsRouteImport } from './routes/_app.qa-amendments'
import { Route as AppReferenceRouteImport } from './routes/_app.reference'
import { Route as AppRevisionRouteImport } from './routes/_app.revision'
import { Route as AppRfpIntakeRouteImport } from './routes/_app.rfp-intake'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppShapingRouteImport } from './routes/_app.shaping'
import { Route as AppSubclientMappingRouteImport } from './routes/_app.subclient-mapping'
import { Route as AppSubmissionRouteImport } from './routes/_app.submission'
import { Route as AppTalentSponsorsRouteImport } from './routes/_app.talent-sponsors'
import { Route as AppTechCostRouteImport } from './routes/_app.tech-cost'
import { Route as AppVenuePitchRouteImport } from './routes/_app.venue-pitch'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as IntakeReviewRouteImport } from './routes/intake.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAwardRoute = AppAwardRouteImport.update({
  id: '/award',
  path: '/award',
  getParentRoute: () => AppRoute,
} as any)
const AppBidDecisionRoute = AppBidDecisionRouteImport.update({
  id: '/bid-decision',
  path: '/bid-decision',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkEditRoute = AppBulkEditRouteImport.update({
  id: '/bulk-edit',
  path: '/bulk-edit',
  getParentRoute: () => AppRoute,
} as any)
const AppCloseoutRoute = AppCloseoutRouteImport.update({
  id: '/closeout',
  path: '/closeout',
  getParentRoute: () => AppRoute,
} as any)
const AppCommsRegistrationRoute = AppCommsRegistrationRouteImport.update({
  id: '/comms-registration',
  path: '/comms-registration',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEventIntakeRoute = AppEventIntakeRouteImport.update({
  id: '/event-intake',
  path: '/event-intake',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionRoute = AppExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionPrepRoute = AppExecutionPrepRouteImport.update({
  id: '/execution-prep',
  path: '/execution-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppFinalizationRoute = AppFinalizationRouteImport.update({
  id: '/finalization',
  path: '/finalization',
  getParentRoute: () => AppRoute,
} as any)
const AppFuturePodsRoute = AppFuturePodsRouteImport.update({
  id: '/future-pods',
  path: '/future-pods',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterMapRoute = AppMasterMapRouteImport.update({
  id: '/master-map',
  path: '/master-map',
  getParentRoute: () => AppRoute,
} as any)
const AppMaturityRoute = AppMaturityRouteImport.update({
  id: '/maturity',
  path: '/maturity',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPod1Route = AppPod1RouteImport.update({
  id: '/pod1',
  path: '/pod1',
  getParentRoute: () => AppRoute,
} as any)
const AppPod2Route = AppPod2RouteImport.update({
  id: '/pod2',
  path: '/pod2',
  getParentRoute: () => AppRoute,
} as any)
const AppPod3Route = AppPod3RouteImport.update({
  id: '/pod3',
  path: '/pod3',
  getParentRoute: () => AppRoute,
} as any)
const AppPostSubmitRoute = AppPostSubmitRouteImport.update({
  id: '/post-submit',
  path: '/post-submit',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppQaAmendmentsRoute = AppQaAmendmentsRouteImport.update({
  id: '/qa-amendments',
  path: '/qa-amendments',
  getParentRoute: () => AppRoute,
} as any)
const AppReferenceRoute = AppReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionRoute = AppRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AppRoute,
} as any)
const AppRfpIntakeRoute = AppRfpIntakeRouteImport.update({
  id: '/rfp-intake',
  path: '/rfp-intake',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppShapingRoute = AppShapingRouteImport.update({
  id: '/shaping',
  path: '/shaping',
  getParentRoute: () => AppRoute,
} as any)
const AppSubclientMappingRoute = AppSubclientMappingRouteImport.update({
  id: '/subclient-mapping',
  path: '/subclient-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionRoute = AppSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentSponsorsRoute = AppTalentSponsorsRouteImport.update({
  id: '/talent-sponsors',
  path: '/talent-sponsors',
  getParentRoute: () => AppRoute,
} as any)
const AppTechCostRoute = AppTechCostRouteImport.update({
  id: '/tech-cost',
  path: '/tech-cost',
  getParentRoute: () => AppRoute,
} as any)
const AppVenuePitchRoute = AppVenuePitchRouteImport.update({
  id: '/venue-pitch',
  path: '/venue-pitch',
  getParentRoute: () => AppRoute,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeReviewRoute = IntakeReviewRouteImport.update({
  id: '/intake/review',
  path: '/intake/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/orientation': typeof OrientationRoute
  '/roles': typeof RolesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/access': typeof AppAccessRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/award': typeof AppAwardRoute
  '/bid-decision': typeof AppBidDecisionRoute
  '/budget': typeof AppBudgetRoute
  '/bulk-edit': typeof AppBulkEditRoute
  '/closeout': typeof AppCloseoutRoute
  '/comms-registration': typeof AppCommsRegistrationRoute
  '/compliance': typeof AppComplianceRoute
  '/connectors': typeof AppConnectorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/event-intake': typeof AppEventIntakeRoute
  '/execution': typeof AppExecutionRoute
  '/execution-prep': typeof AppExecutionPrepRoute
  '/finalization': typeof AppFinalizationRoute
  '/future-pods': typeof AppFuturePodsRoute
  '/goals': typeof AppGoalsRoute
  '/master-map': typeof AppMasterMapRoute
  '/maturity': typeof AppMaturityRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/overview': typeof AppOverviewRoute
  '/pipeline': typeof AppPipelineRoute
  '/pod1': typeof AppPod1Route
  '/pod2': typeof AppPod2Route
  '/pod3': typeof AppPod3Route
  '/post-submit': typeof AppPostSubmitRoute
  '/production': typeof AppProductionRoute
  '/proposals': typeof AppProposalsRoute
  '/qa-amendments': typeof AppQaAmendmentsRoute
  '/reference': typeof AppReferenceRoute
  '/revision': typeof AppRevisionRoute
  '/rfp-intake': typeof AppRfpIntakeRoute
  '/roadmap': typeof AppRoadmapRoute
  '/shaping': typeof AppShapingRoute
  '/subclient-mapping': typeof AppSubclientMappingRoute
  '/submission': typeof AppSubmissionRoute
  '/talent-sponsors': typeof AppTalentSponsorsRoute
  '/tech-cost': typeof AppTechCostRoute
  '/venue-pitch': typeof AppVenuePitchRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/orientation': typeof OrientationRoute
  '/roles': typeof RolesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/access': typeof AppAccessRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit': typeof AppAuditRoute
  '/award': typeof AppAwardRoute
  '/bid-decision': typeof AppBidDecisionRoute
  '/budget': typeof AppBudgetRoute
  '/bulk-edit': typeof AppBulkEditRoute
  '/closeout': typeof AppCloseoutRoute
  '/comms-registration': typeof AppCommsRegistrationRoute
  '/compliance': typeof AppComplianceRoute
  '/connectors': typeof AppConnectorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/event-intake': typeof AppEventIntakeRoute
  '/execution': typeof AppExecutionRoute
  '/execution-prep': typeof AppExecutionPrepRoute
  '/finalization': typeof AppFinalizationRoute
  '/future-pods': typeof AppFuturePodsRoute
  '/goals': typeof AppGoalsRoute
  '/master-map': typeof AppMasterMapRoute
  '/maturity': typeof AppMaturityRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/overview': typeof AppOverviewRoute
  '/pipeline': typeof AppPipelineRoute
  '/pod1': typeof AppPod1Route
  '/pod2': typeof AppPod2Route
  '/pod3': typeof AppPod3Route
  '/post-submit': typeof AppPostSubmitRoute
  '/production': typeof AppProductionRoute
  '/proposals': typeof AppProposalsRoute
  '/qa-amendments': typeof AppQaAmendmentsRoute
  '/reference': typeof AppReferenceRoute
  '/revision': typeof AppRevisionRoute
  '/rfp-intake': typeof AppRfpIntakeRoute
  '/roadmap': typeof AppRoadmapRoute
  '/shaping': typeof AppShapingRoute
  '/subclient-mapping': typeof AppSubclientMappingRoute
  '/submission': typeof AppSubmissionRoute
  '/talent-sponsors': typeof AppTalentSponsorsRoute
  '/tech-cost': typeof AppTechCostRoute
  '/venue-pitch': typeof AppVenuePitchRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake': typeof IntakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/help': typeof HelpRoute
  '/orientation': typeof OrientationRoute
  '/roles': typeof RolesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/award': typeof AppAwardRoute
  '/_app/bid-decision': typeof AppBidDecisionRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/bulk-edit': typeof AppBulkEditRoute
  '/_app/closeout': typeof AppCloseoutRoute
  '/_app/comms-registration': typeof AppCommsRegistrationRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/event-intake': typeof AppEventIntakeRoute
  '/_app/execution': typeof AppExecutionRoute
  '/_app/execution-prep': typeof AppExecutionPrepRoute
  '/_app/finalization': typeof AppFinalizationRoute
  '/_app/future-pods': typeof AppFuturePodsRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/master-map': typeof AppMasterMapRoute
  '/_app/maturity': typeof AppMaturityRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/pod1': typeof AppPod1Route
  '/_app/pod2': typeof AppPod2Route
  '/_app/pod3': typeof AppPod3Route
  '/_app/post-submit': typeof AppPostSubmitRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/proposals': typeof AppProposalsRoute
  '/_app/qa-amendments': typeof AppQaAmendmentsRoute
  '/_app/reference': typeof AppReferenceRoute
  '/_app/revision': typeof AppRevisionRoute
  '/_app/rfp-intake': typeof AppRfpIntakeRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/shaping': typeof AppShapingRoute
  '/_app/subclient-mapping': typeof AppSubclientMappingRoute
  '/_app/submission': typeof AppSubmissionRoute
  '/_app/talent-sponsors': typeof AppTalentSponsorsRoute
  '/_app/tech-cost': typeof AppTechCostRoute
  '/_app/venue-pitch': typeof AppVenuePitchRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/orientation'
    | '/roles'
    | '/signin'
    | '/signup'
    | '/start'
    | '/access'
    | '/approvals'
    | '/audit'
    | '/award'
    | '/bid-decision'
    | '/budget'
    | '/bulk-edit'
    | '/closeout'
    | '/comms-registration'
    | '/compliance'
    | '/connectors'
    | '/dashboard'
    | '/documents'
    | '/event-intake'
    | '/execution'
    | '/execution-prep'
    | '/finalization'
    | '/future-pods'
    | '/goals'
    | '/master-map'
    | '/maturity'
    | '/opportunities'
    | '/overview'
    | '/pipeline'
    | '/pod1'
    | '/pod2'
    | '/pod3'
    | '/post-submit'
    | '/production'
    | '/proposals'
    | '/qa-amendments'
    | '/reference'
    | '/revision'
    | '/rfp-intake'
    | '/roadmap'
    | '/shaping'
    | '/subclient-mapping'
    | '/submission'
    | '/talent-sponsors'
    | '/tech-cost'
    | '/venue-pitch'
    | '/intake/review'
    | '/intake/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/orientation'
    | '/roles'
    | '/signin'
    | '/signup'
    | '/start'
    | '/access'
    | '/approvals'
    | '/audit'
    | '/award'
    | '/bid-decision'
    | '/budget'
    | '/bulk-edit'
    | '/closeout'
    | '/comms-registration'
    | '/compliance'
    | '/connectors'
    | '/dashboard'
    | '/documents'
    | '/event-intake'
    | '/execution'
    | '/execution-prep'
    | '/finalization'
    | '/future-pods'
    | '/goals'
    | '/master-map'
    | '/maturity'
    | '/opportunities'
    | '/overview'
    | '/pipeline'
    | '/pod1'
    | '/pod2'
    | '/pod3'
    | '/post-submit'
    | '/production'
    | '/proposals'
    | '/qa-amendments'
    | '/reference'
    | '/revision'
    | '/rfp-intake'
    | '/roadmap'
    | '/shaping'
    | '/subclient-mapping'
    | '/submission'
    | '/talent-sponsors'
    | '/tech-cost'
    | '/venue-pitch'
    | '/intake/review'
    | '/intake'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/help'
    | '/orientation'
    | '/roles'
    | '/signin'
    | '/signup'
    | '/start'
    | '/_app/access'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/award'
    | '/_app/bid-decision'
    | '/_app/budget'
    | '/_app/bulk-edit'
    | '/_app/closeout'
    | '/_app/comms-registration'
    | '/_app/compliance'
    | '/_app/connectors'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/event-intake'
    | '/_app/execution'
    | '/_app/execution-prep'
    | '/_app/finalization'
    | '/_app/future-pods'
    | '/_app/goals'
    | '/_app/master-map'
    | '/_app/maturity'
    | '/_app/opportunities'
    | '/_app/overview'
    | '/_app/pipeline'
    | '/_app/pod1'
    | '/_app/pod2'
    | '/_app/pod3'
    | '/_app/post-submit'
    | '/_app/production'
    | '/_app/proposals'
    | '/_app/qa-amendments'
    | '/_app/reference'
    | '/_app/revision'
    | '/_app/rfp-intake'
    | '/_app/roadmap'
    | '/_app/shaping'
    | '/_app/subclient-mapping'
    | '/_app/submission'
    | '/_app/talent-sponsors'
    | '/_app/tech-cost'
    | '/_app/venue-pitch'
    | '/intake/review'
    | '/intake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HelpRoute: typeof HelpRoute
  OrientationRoute: typeof OrientationRoute
  RolesRoute: typeof RolesRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  IntakeReviewRoute: typeof IntakeReviewRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/award': {
      id: '/_app/award'
      path: '/award'
      fullPath: '/award'
      preLoaderRoute: typeof AppAwardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bid-decision': {
      id: '/_app/bid-decision'
      path: '/bid-decision'
      fullPath: '/bid-decision'
      preLoaderRoute: typeof AppBidDecisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bulk-edit': {
      id: '/_app/bulk-edit'
      path: '/bulk-edit'
      fullPath: '/bulk-edit'
      preLoaderRoute: typeof AppBulkEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/closeout': {
      id: '/_app/closeout'
      path: '/closeout'
      fullPath: '/closeout'
      preLoaderRoute: typeof AppCloseoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comms-registration': {
      id: '/_app/comms-registration'
      path: '/comms-registration'
      fullPath: '/comms-registration'
      preLoaderRoute: typeof AppCommsRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event-intake': {
      id: '/_app/event-intake'
      path: '/event-intake'
      fullPath: '/event-intake'
      preLoaderRoute: typeof AppEventIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/execution': {
      id: '/_app/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof AppExecutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/execution-prep': {
      id: '/_app/execution-prep'
      path: '/execution-prep'
      fullPath: '/execution-prep'
      preLoaderRoute: typeof AppExecutionPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finalization': {
      id: '/_app/finalization'
      path: '/finalization'
      fullPath: '/finalization'
      preLoaderRoute: typeof AppFinalizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/future-pods': {
      id: '/_app/future-pods'
      path: '/future-pods'
      fullPath: '/future-pods'
      preLoaderRoute: typeof AppFuturePodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-map': {
      id: '/_app/master-map'
      path: '/master-map'
      fullPath: '/master-map'
      preLoaderRoute: typeof AppMasterMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maturity': {
      id: '/_app/maturity'
      path: '/maturity'
      fullPath: '/maturity'
      preLoaderRoute: typeof AppMaturityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pod1': {
      id: '/_app/pod1'
      path: '/pod1'
      fullPath: '/pod1'
      preLoaderRoute: typeof AppPod1RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pod2': {
      id: '/_app/pod2'
      path: '/pod2'
      fullPath: '/pod2'
      preLoaderRoute: typeof AppPod2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pod3': {
      id: '/_app/pod3'
      path: '/pod3'
      fullPath: '/pod3'
      preLoaderRoute: typeof AppPod3RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post-submit': {
      id: '/_app/post-submit'
      path: '/post-submit'
      fullPath: '/post-submit'
      preLoaderRoute: typeof AppPostSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qa-amendments': {
      id: '/_app/qa-amendments'
      path: '/qa-amendments'
      fullPath: '/qa-amendments'
      preLoaderRoute: typeof AppQaAmendmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reference': {
      id: '/_app/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof AppReferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revision': {
      id: '/_app/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AppRevisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfp-intake': {
      id: '/_app/rfp-intake'
      path: '/rfp-intake'
      fullPath: '/rfp-intake'
      preLoaderRoute: typeof AppRfpIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shaping': {
      id: '/_app/shaping'
      path: '/shaping'
      fullPath: '/shaping'
      preLoaderRoute: typeof AppShapingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subclient-mapping': {
      id: '/_app/subclient-mapping'
      path: '/subclient-mapping'
      fullPath: '/subclient-mapping'
      preLoaderRoute: typeof AppSubclientMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submission': {
      id: '/_app/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof AppSubmissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talent-sponsors': {
      id: '/_app/talent-sponsors'
      path: '/talent-sponsors'
      fullPath: '/talent-sponsors'
      preLoaderRoute: typeof AppTalentSponsorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tech-cost': {
      id: '/_app/tech-cost'
      path: '/tech-cost'
      fullPath: '/tech-cost'
      preLoaderRoute: typeof AppTechCostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venue-pitch': {
      id: '/_app/venue-pitch'
      path: '/venue-pitch'
      fullPath: '/venue-pitch'
      preLoaderRoute: typeof AppVenuePitchRouteImport
      parentRoute: typeof AppRoute
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/review': {
      id: '/intake/review'
      path: '/intake/review'
      fullPath: '/intake/review'
      preLoaderRoute: typeof IntakeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppAwardRoute: typeof AppAwardRoute
  AppBidDecisionRoute: typeof AppBidDecisionRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppBulkEditRoute: typeof AppBulkEditRoute
  AppCloseoutRoute: typeof AppCloseoutRoute
  AppCommsRegistrationRoute: typeof AppCommsRegistrationRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEventIntakeRoute: typeof AppEventIntakeRoute
  AppExecutionRoute: typeof AppExecutionRoute
  AppExecutionPrepRoute: typeof AppExecutionPrepRoute
  AppFinalizationRoute: typeof AppFinalizationRoute
  AppFuturePodsRoute: typeof AppFuturePodsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMasterMapRoute: typeof AppMasterMapRoute
  AppMaturityRoute: typeof AppMaturityRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPod1Route: typeof AppPod1Route
  AppPod2Route: typeof AppPod2Route
  AppPod3Route: typeof AppPod3Route
  AppPostSubmitRoute: typeof AppPostSubmitRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppQaAmendmentsRoute: typeof AppQaAmendmentsRoute
  AppReferenceRoute: typeof AppReferenceRoute
  AppRevisionRoute: typeof AppRevisionRoute
  AppRfpIntakeRoute: typeof AppRfpIntakeRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppShapingRoute: typeof AppShapingRoute
  AppSubclientMappingRoute: typeof AppSubclientMappingRoute
  AppSubmissionRoute: typeof AppSubmissionRoute
  AppTalentSponsorsRoute: typeof AppTalentSponsorsRoute
  AppTechCostRoute: typeof AppTechCostRoute
  AppVenuePitchRoute: typeof AppVenuePitchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppAwardRoute: AppAwardRoute,
  AppBidDecisionRoute: AppBidDecisionRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppBulkEditRoute: AppBulkEditRoute,
  AppCloseoutRoute: AppCloseoutRoute,
  AppCommsRegistrationRoute: AppCommsRegistrationRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEventIntakeRoute: AppEventIntakeRoute,
  AppExecutionRoute: AppExecutionRoute,
  AppExecutionPrepRoute: AppExecutionPrepRoute,
  AppFinalizationRoute: AppFinalizationRoute,
  AppFuturePodsRoute: AppFuturePodsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMasterMapRoute: AppMasterMapRoute,
  AppMaturityRoute: AppMaturityRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPod1Route: AppPod1Route,
  AppPod2Route: AppPod2Route,
  AppPod3Route: AppPod3Route,
  AppPostSubmitRoute: AppPostSubmitRoute,
  AppProductionRoute: AppProductionRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppQaAmendmentsRoute: AppQaAmendmentsRoute,
  AppReferenceRoute: AppReferenceRoute,
  AppRevisionRoute: AppRevisionRoute,
  AppRfpIntakeRoute: AppRfpIntakeRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppShapingRoute: AppShapingRoute,
  AppSubclientMappingRoute: AppSubclientMappingRoute,
  AppSubmissionRoute: AppSubmissionRoute,
  AppTalentSponsorsRoute: AppTalentSponsorsRoute,
  AppTechCostRoute: AppTechCostRoute,
  AppVenuePitchRoute: AppVenuePitchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HelpRoute: HelpRoute,
  OrientationRoute: OrientationRoute,
  RolesRoute: RolesRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  IntakeReviewRoute: IntakeReviewRoute,
  IntakeIndexRoute: IntakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
